### ISSUE TITLE
Trajectory attribute for all box objects

### ISSUE THREAD

**Issue by bdice** [glotzerlab/garnett#108]
## Description

I would like to be able to access box objects from every frame as a trajectory property, as a list of `garnett.trajectory.Box` objects.

## Proposed solution

Similar to existing trajectory attributes, except not as a NumPy array (just a list).

## Additional context

Many boxes: 🗳 🗃 ☑️ 🥊

**Comment by lyrivera** [comment]
such boxes many wows

**Comment by lyrivera** [comment]
This may be convenient for some of my recent work. I'll tackle it.
