### ISSUE TITLE
Old Links

### ISSUE THREAD

**Issue by j-proc** [glotzerlab/garnett#115]
Package description still references glotzformats.

**Comment by bdice** [comment]
@j-proc Can you provide a link or line number in the docs/code?

**Comment by j-proc** [comment]
Not in the docs I think. On the site. I'm assuming only package maintainer
can change but I'll check.

**Comment by lyrivera** [comment]
> On the site. I'm assuming only package maintainer can change but I'll check.

@j-proc Other that some commit comments, I can't find any instance of the name `glotzformats` in the current state of the package. Perhaps you still have some remnants of an old installation?

**Comment by j-proc** [comment]
@lyrivera bdice says he can edit it directly.

**Comment by bdice** [comment]
It was the "homepage" link in the GitHub repo header -- I fixed it to point to https://garnett.readthedocs.io/. Thanks for the catch @j-proc!

**Comment by lyrivera** [comment]
> It was the "homepage" link in the GitHub repo header -- I fixed it to point to https://garnett.readthedocs.io/. Thanks for the catch @j-proc!

Got it. Thanks @j-proc.
