### ISSUE TITLE
Use types and typeid properties consistent with HOOMD

### ISSUE THREAD

**Issue by bdice** [glotzerlab/garnett#137]
## Description

The properties for type names and ids are inconsistent with HOOMD, and within the Trajectory / Frame APIs.

|  API     | HOOMD/GSD                                     | garnett Frame                                       | garnett Trajectory                                                     |
|----------|-----------------------------------------------|-----------------------------------------------------|------------------------------------------------------------------------|
| type     | N/A                                           | N/A                                                 | array of N_types strings, ['A', 'B', 'C']                              |
| types    | array of N_types  strings, ['A', 'B', 'C']    | array of N_particles  strings, ['A', 'A', 'B', ...] | array of (N_frames, N_particles)  strings, [['A', 'A', 'B', ...], ...] |
| typeid   | array of N_particles indices,  [0, 0, 1, ...] | N/A                                                 | N/A                                                                    |
| type_ids | N/A                                           | N/A                                                 |                                                                        |

## Proposed solution

Refactor in reader classes:
- The type id (unsigned integer) should be the "fundamental" identifier, not the type name string

Refactor in Trajectory:
- `types` should be removed
- `type` should be removed
- `types` should be a list of lists of strings with unique types for each frame (N_frames, N_types)
- `type_ids` should become `typeid`

Refactor in Frame:
- `types` should be a list of type name strings
- `typeid` should be an array of integer type indices

## Additional context

N/A

**Comment by klarh** [comment]
Might I suggest `type_names` as the name for the quantity that is a list of unique strings (`['A', 'B', 'C']`)? I think that any time we have something called `type` or `types`, it will be a point of likely confusion, especially when it gets changed over time and between libraries.

**Comment by bdice** [comment]
@klarh We're aiming for consistency with the current conventions of HOOMD and GSD. Overall, we're positioning garnett as a tool that is meant to track the core features of HOOMD data files and historical data generated by HOOMD, since that is what provides the most value in our group. People mostly know the HOOMD/GSD conventions already, and garnett's current implementation is ... worth improving.

**Comment by bdice** [comment]
@klarh I understand your concern. I think breaking the API as we have already done (e.g. `positions` to `position`) is in the long term interest of our group’s users. We are planning to adhere to semantic versioning and make the API stable with a future 1.0 release. I agree that API changes are detrimental in the short term but hope that this can reduce users’ longstanding confusion over data fields. Our current users are overwhelmingly adherent to and knowledgeable about HOOMD/GSD property conventions, and sticking closely to that seems better than adopting a custom set of conventions.
