### ISSUE TITLE
Update GSD reader/writer for GSD 2.0

### ISSUE THREAD

**Issue by bdice** [glotzerlab/garnett#140]
## Description

GSD has deprecated some features in preparation for the 2.0 release. The GSD reader/writer needs to be refactored to use the newer APIs. Additional info: https://github.com/glotzerlab/gsd/pull/63

## Proposed solution

Update GSD reader/writer.

**Comment by joaander** [comment]
Suggested changes:
* Update the embedded `gsdhoomd.py` file to the latest version.
* Use `gsd.hoomd.open`on line 292 of `gsdhoomdfilereader.py`
