### ISSUE TITLE
Docs won't build with cython >=0.29.0

### ISSUE THREAD

**Issue by bdice** [glotzerlab/garnett#46]
I was having issues building the docs, which I've finally tracked down. The failures were with the `dcdreader` module, which is built with Cython. The error message below only appears when I try to build the documentation with sphinx. The package builds and installs just fine without any warnings. I could import the `dcdreader` class in a Python shell even though Sphinx failed to import that module. I did not try to execute the tests.

There seems to be a bug with Cython >=0.29.0 (the latest version is 0.29.6). The errors are introduced by the changes in this line, specifically the `check_size ignore` part: https://github.com/cython/cython/blame/477c152e4004b4bf581e1a05f5b24bd56dea87db/Cython/Includes/numpy/__init__.pxd#L206

This error message was repeated many times, for every attempt to import a class for Sphinx to extract docstrings.
```python
WARNING: autodoc: failed to import class 'formats.FileFormat' from module 'glotzformats'; the following exception was raised:
Traceback (most recent call last):
  File "/.../lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 232, in import_module
    __import__(modname)
  File "/.../glotzformats/glotzformats/__init__.py", line 7, in <module>
    from . import reader
  File "/.../glotzformats/glotzformats/reader.py", line 39, in <module>
    from . import dcdreader
  File "__init__.pxd", line 206, in init glotzformats.dcdreader
TypeError: numpy.dtype is not a type object
```
By using Cython 0.28.5, I was able to fix this problem and build the docs.

**Comment by lyrivera** [comment]
Seems like this has been addressed by @klarh on #104. I am now able to build the docs with `cython=0.29.0`
