### ISSUE TITLE
Use data formats and names consistent with HOOMD 

### ISSUE THREAD

**Issue by klywang** [glotzerlab/garnett#73]
Would we be interested in using the same names and data formats in glotzformats as we do with HOOMD?

I'm specifically referring to, `frame.types`, which returns a Nx1 array `['A', 'A', .., 'B']`. With HOOMD, `snap.particles.types` would return the unique particles types in the system, ie `['A', 'B']` and `snap.particles.typeid` returns a Nx1 array `[0, 0, .., 1]`. I'm also not sure why `type_ids` can be accessed from the `Trajectory` class but not from the `Frame` class although that may be a separate issue.

`frame.velocities` and `snap.particles.velocity` also return the same information but it would be nice if the names were consistent.

Those were the only two inconsistencies I'm aware of at the moment. 

If we decided to do this, I'm not entirely sure where this falls in terms of priority, but it would make it easier to transition between using HOOMD and glotzformats.

**Comment by lyrivera** [comment]
Closing this issue now since all these proposed changes are covered in #76.
