### ISSUE TITLE
Set frame.types and traj.types to return unique list of ids

### ISSUE THREAD

**Issue by klywang** [glotzerlab/garnett#74]
`frame.types` should return the same output as `snap.particles.types` to maintain consistency with HOOMD. We should try to minimize difference between data access in HOOMD and garnett (Extension of #73)

Task checklist:
* Refactor `frame.types` output to array of unique string identifies for particle types in the file
* Update unit tests accordingly
* Add release tag/warning so users are aware of the change

**Comment by lyrivera** [comment]
This is covered in #76.
