### ISSUE TITLE
Add type_ids to Frame class

### ISSUE THREAD

**Issue by klywang** [glotzerlab/garnett#75]
`type_ids` is only accessable from the loaded `Trajectory` class. `frame.types` currently returns an analagout list of strings to `traj.type_ids` but lacks a way to access `type_ids` directly. This is inconsistent with HOOMD's data access convention and forces users to load the `Trajectory` class to get information on individual patricle properties.

Task list:
* Add `frame.type_ids`
* Add unit tests
* Add deprecation warning for those who use `frame.types` for this purpose

Extension of #73

**Comment by lyrivera** [comment]
This changes will be addressed in #76.
