### ISSUE TITLE
Universal reader does not support templates for DCD files

### ISSUE THREAD

**Issue by klywang** [glotzerlab/garnett#82]
The following code:
`with glotzformats.read('dump.gsd', 'dump.pos') as traj:`
Lets you use POS or XML files as a template for GSD files.

To use POS or XML files as templates for DCD files, seperate readers must be used.
For example:
`frame = glotzformats.reader.PosFileReader().read(open('dump.pos', 'r'))[0]`
`traj = glotzformats.reader.DCDFileReader().read(open('dump.dcd', 'rb'), frame)`

Do we want to make this more consistent? I'm not sure how popular DCD files are vs how important it this sort of consistency is.

**Comment by lyrivera** [comment]
Closing this for now. Can be addressed later if needed.
