### ISSUE TITLE
Refactor GSD into a hard/soft dependency

### ISSUE THREAD

**Issue by bdice** [glotzerlab/garnett#89]
Currently, this package offers support for GSD files in two ways. If the user has the GSD native reader installed (e.g. via `pip install gsd`), then we use the native reader. Otherwise, the files `pygsd.py` and `gsdhoomd.py` implement the Python-only reader copied directly from the GSD package.

I suggest that we simplify this so that GSD is a hard (or soft) dependency with no implementation provided directly within this package. I'm in favor of it being a hard dependency but would be open to making it a soft dependency.

Reasons:
1. Our implementation copied from GSD tends to be outdated.
2. The Python-only reader is probably slower than the native reader of the GSD package (not benchmarked).
3. Triggering users to install the GSD package presents only a small barrier since GSD is widely supported.
4. The GSD package is already required as a [dependency for MDAnalysis](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L562) so I think it's reasonable to require it for this package as well.

**Comment by bdice** [comment]
I'm changing my mind about this and I think the issue can be closed after #157. We now have a clearer picture of our soft/hard dependencies. Both the minimal and maximal set of dependencies are tested.

**Comment by joaander** [comment]
@csadorf @bdice A future version of GSD will support reading in-memory buffers with the C implementation: https://github.com/glotzerlab/gsd/issues/64
